### ISSUE TITLE
Robot.getColourSensor() / ColourSensor

### ISSUE THREAD

**Issue by Robadob** [ramsay-t/ShefRobot#11]
Wrap [this](http://www.lejos.org/ev3/docs/lejos/hardware/sensor/EV3ColorSensor.html) class presumably.

Originally thought this was the IR sensor, but [Lego shop shows it to be the color sensor](http://shop.lego.com/en-GB/EV3-Color-Sensor-45506).

---

**The question is whether to use the American spelling of Color, as is standard throughout programming or correct it to the proper spelling.**

**Comment by ramsay-t** [comment]
Have a look at the internals of ShefRobot.Sensor - I think there is an RMIRemoteSensor object that takes a type or something. be careful with the classes - although the package contains the NXT ones for backward compatibility I’m trying to stick to the explicitly EV3 ones…

**Comment by Robadob** [comment]
I must be tired, that was just a mistake me linking to NXT rather than EV3, fixed it in the OP now.

**Comment by Robadob** [comment]
Do you want me to use `Colour` or `Color`?

I'm undecided, one is English, the other is tradition.

**Comment by Robadob** [comment]
`EasyGraphics` uses `Color`, so I'll stick with that for consistency
.

**Comment by ramsay-t** [comment]
Both, and then one should call the other ;)

**Comment by Robadob** [comment]
I'm guessing you implemented sensors to use [`createSampleProvider()`](http://www.lejos.org/ev3/docs/lejos/remote/ev3/RemoteEV3.html#createSampleProvider-java.lang.String-java.lang.String-java.lang.String-) (aka your provided with an [`RMIRemoteSampleProvider`](http://www.lejos.org/ev3/docs/lejos/remote/ev3/RMIRemoteSampleProvider.html)) because you read [this](http://sourceforge.net/p/lejos/wiki/Remote%20access%20to%20an%20EV3/) guide and wanted the alleged lower latency.

I'm going to switch to the other method (for all sensors), because otherwise it's not possible to access features other than `fetchSample()`, this includes the internal methods used by each sensor to calibrate the value returned from the sensor.

**Comment by Robadob** [comment]
Alternatively I could try reimplementing my own `RMIRemoteSampleProvider` so I can access the damn BaseSensor which is private.

``` Java
public class RMIRemoteSampleProvider extends UnicastRemoteObject
  implements RMISampleProvider
{
  private static final long serialVersionUID = -8432755905878519147L;
  private SampleProvider provider;
  private BaseSensor sensor;
  private int sampleSize;

  protected RMIRemoteSampleProvider(String portName, String sensorName, String modeName)
    throws RemoteException
  {
    super(0);
    try {
      Class c = Class.forName(sensorName);
      Class[] params = new Class[1];
      params[0] = Port.class;
      Constructor con = c.getConstructor(params);
      Object[] args = new Object[1];
      args[0] = LocalEV3.get().getPort(portName);
      this.sensor = ((BaseSensor)con.newInstance(args));
      if (modeName == null) this.provider = this.sensor; else
        this.provider = this.sensor.getMode(modeName);
      this.sampleSize = this.provider.sampleSize();
    } catch (Exception e) {
      if (this.sensor != null) this.sensor.close();
      throw new DeviceException("Failed to create sample provider", e);
    }
  }

  public float[] fetchSample() throws RemoteException
  {
    float[] sample = new float[this.sampleSize];
    this.provider.fetchSample(sample, 0);
    return sample;
  }

  public void close() throws RemoteException
  {
    if (this.sensor != null) this.sensor.close();
  }
}
```

**Comment by ramsay-t** [comment]
We can go with that explanation if you like - I think it was just more obvious form the RemoteEV3 API… ;)

Remember that we don’t want to make things too easy for the students, we might want to leave calibration as an exercise for them. Assuming thats sensible - if there are calibrations available for sensors that have binary responses (like the touch sensor) then it might be important; if the sensors return floats and its up to you to work out what that means then we might not want to help too much.

**Comment by Robadob** [comment]
> Remember that we don’t want to make things too easy for the students

It's quicker to remove functionality last minute, than to add it.

**Comment by Robadob** [comment]
I've now written most of the Color sensor, of the 4 modes;
- Color Mode: Returns an enum based on 1 of 8(?) colours that has been detected
- Red Mode: Returns a float in the range 0-0.5 based on the level of reflected red light
- Ambient Mode: Returns a float in the range 0-0.2 based on the level of reflected blue light (I'm pretty sure this mode is faulty, the docs say it use ambient light, but it enables the blue light and the small range of values make it pretty insensitive)
- RGB Mode: Whatever I use to sample the values returned whilst in this mode, all I  receive is an array of 0's. So I've disabled it.

**Comment by ramsay-t** [comment]
Their first task is to find and follow a black line on a pale background. Is there some sort of greyscale intensity mode?

**Comment by Robadob** [comment]
That's supposed to be the ambient mode, but it doesn't look very promising.

A red line would work though!

**Comment by Robadob** [comment]
There seems to be discussion about it here;

http://www.lejos.org/forum/viewtopic.php?t=5327

**Comment by ramsay-t** [comment]
Well, technically, white tile will reflect more red than black tape……

**Comment by ramsay-t** [comment]
I haven’t got one in front of me. By the sounds of it its really a light sensor with an RGB LED, so if you activate the Red LED and then detect light levels you are detecting Red colour reflection, ditto Blue and Green etc. 

To follow a black line you want to turn on white light and then measure light levels…

**Comment by Robadob** [comment]
Except at a hardware level, when you request a sample of a certain type, it
forcibly sets the LED to a certain state and only returns the processed
value.

It doesn't make much sense to me why the returned value of ambient appears
capped to 0.2, but red 0.5, the docs state all 3 are normalised to 0-1.

**Comment by Robadob** [comment]
http://www.lejos.org/forum/viewtopic.php?t=7412

This suggests blue is just less sensitive on them, and alot of variance
between sensors.

Still doesn't explain the 0's I've been receiving for RGB mode, ill try
that mode again.

**Comment by ramsay-t** [comment]
The light sensor will be more responsive to certain frequency ranges, and the glass/plastic lens will refract and reflect different frequencies away from the sensor…

Or the software is crap :)

**Comment by Robadob** [comment]
Similarly, GyroSensor is returning -0.0 continuously...

Seeing as I've done the core functionality now, I'll take a walk to the
Diamond and test the robot there, see if I can port over my 1st year robot
assignment.

**Comment by ramsay-t** [comment]
Or you have plugged the cable in wrong, or you happen to have picked a broken one ;)

**Comment by Robadob** [comment]
I tried 2 cables and multiple sensor ports, don't have a second gyro to
test with.

Pretty crap luck if two sensors on this Robot are dodgy.

_On the upside, the firewall changes has worked, you can control robots
from Diamond machines!_

**Comment by ramsay-t** [comment]
> On 8 Nov 2015, at 13:03, Robert Chisholm notifications@github.com wrote:
> 
> I tried 2 cables and multiple sensor ports, don't have a second gyro to
> test with.
> 
> Pretty crap luck if two sensors on this Robot are dodgy.

That is the one that has been kicking around the office for a while...

> _On the upside, the firewall changes has worked, you can control robots
> from Diamond machines!_

Cool! Lets keep tomorrows appointment and go through the worksheet and make nice screen shots. I suspect that if you use the terminals next to the door next to the high performance room (we need a better naming scheme) you will find that Robot C5 is already paired, so we may have to make the instructions more subtle….

**Comment by Robadob** [comment]
Doesn't appear that I can do any more testing, the battery appears to have
run out [and I've just finished assembling and porting the assignment code
:( ].

I had assumed that you could charge it via the mini-usb port, but that
appears to not be the case (I've just noticed a charging port directly on
the battery pack).

**Comment by ramsay-t** [comment]
There is a direct charge port but they are supposed to charge in the cabinets, so we have been keeping the chargers in there. I had assumed that that robot had one with it, but then again I might have left it on my desk :)

**Comment by ramsay-t** [comment]
I think you can stick AAs in, but I don’t expect you to go and buy some.

Incidentally, you definitely didn’t borrow that robot officially from the Diamond, otherwise I should have written a painfully long risk assessment about you blowing up Lithium batteries!! :)

Ramsay

**Comment by Robadob** [comment]
Yeah, I don't have more than 4 AA batteries back at my flat 2 in the TV remote and 2 in a game controller.

I'll just do other stuff that don't require the robot.

**Comment by Robadob** [comment]
Closing because the code is done.
