### ISSUE TITLE
Refactor motors

### ISSUE THREAD

**Issue by Robadob** [ramsay-t/ShefRobot#12]
Refactor Motors into two separate objects (that extend an abstract motor) and methods (`getLargeMotor(Port )` & `getSmallMotor(Port )`), dump motor objects into a motor package at the same time.

**Comment by ramsay-t** [comment]
LargeMotor and Medium motor should be nothing more than subclasses of motor whose constructors take a port and then call super(port,Type.L) and super(port,Type.M) respectively!
