### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by Robadob** [ramsay-t/ShefRobot#15]
Need to find the appropriate parameters to generate the docs at some point.

Last night discovered that the parameter `-protected` will hide all protected scope classes/method/members from the Java-docs, this should be good for hiding the internal classes and methods from meddling students.

Similarly I previously mentioned the `-link http://docs.oracle.com/javase/8/docs/api/` command, better explained [here](http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDEDJFI), that _should_ resolve any  external Java objects properly (Might also be worth adding a second `-link` to the lejos docs, however hopefully that should be 100% hidden.

**Comment by ramsay-t** [comment]
Can we make a Makefile, or will that upset you? I don’t know whether Ant has been replaced by Maven these days, and I don’t want to learn either, never mind the wrong one! :)

**Comment by Robadob** [comment]
I have a couple of .bat files that aren't committed (because I haven't
configured them to build to proper directories, they just dump stuff next
to the source) I've been using. Not got a problem with you making build
scripts, never really used Ant/maven aside from begrudgingly on the rare
occasions I've used 3rd party Java code.

**Comment by Robadob** [comment]
It might just be cleaner to add the particular commands to the README.md
though, seeing as they should be a single command for each.

**Comment by ramsay-t** [comment]
But autoconf can detect paths and stuff ;) I might make a Makefile because thats the most generic way of collecting build commands for different tasks: compile, make-jar, docs  etc.

**Comment by Robadob** [comment]
Go for it, just never come across `makefiles` for Java. Used qmake before for a 4th year project and also built a bunch of libraries using cmake.

**Comment by Robadob** [comment]
``` bat
javadoc -d docs -public -link http://docs.oracle.com/javase/8/docs/api/ -link http://www.lejos.org/ev3/docs/ -subpackages ShefRobot
```

That command builds the docs, just going to try and fix any visible issues with them now

**Comment by Robadob** [comment]
Latest docs are available [here](http://staffwww.dcs.shef.ac.uk/people/R.Chisholm/docs/), in the latest commit to my fork I've also added the above command to the the Readme.md.

I'll leave it upto you to add anything fancy like package overview pages.

**Comment by Robadob** [comment]
I've now also updated the README.md file in my fork to include commands for cleanly building the library and jar file.

Visible [here](https://github.com/Robadob/ShefRobot).

**Comment by Robadob** [comment]
``` bat
@echo OFF
set CLASSPATH=.;bluecove-2.1.0.jar;ShefRobot.jar;dbusjava.jar;ev3classes.jar;%classpath%
```
