### ISSUE TITLE
Fix setupConsole.sh

### ISSUE THREAD

**Issue by Robadob** [ramsay-t/ShefRobot#26]
`setupConsole.sh` needs the first line removing
Also need to adjust the guide to say to run `source setupConsole.sh` rather than just calling the file.

At the same time it would be useful to create a readme in ShefRobot.zip repeating the information about using it from the overview page.

@ptheywood suggested using releases to provide these downloads, rather than having to keep updating the gh-pages branch.

**Comment by ramsay-t** [comment]
I was intending to do releases we just never got round to it.

On 12 November 2015 14:07:46 GMT+00:00, Robert Chisholm notifications@github.com wrote:

> `setupConsole.sh` needs the first line removing
> Also need to adjust the guide to say to run `source setupConsole.sh`
> rather than just calling the file.
> 
> At the same time it would be useful to create a readme in ShefRobot.zip
> repeating the information about using it from the overview page.
> 
> @ptheywood suggested using releases to provide these downloads, rather
> than having to keep updating the gh-pages branch.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ramsay-t/ShefRobot/issues/26

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Robadob** [comment]
Well at current, I've just got the binaries in the gh-pages branch, Pete
just pointed out that doing releases would mean we could point the binary
downloads at the 'latest' release url, rather than having to keep updating
gh-pages when the docs haven't been touched.

It shouldn't be too significant, I'll do it after work tonight.

---

Re todays robots, the only issues were;

a) My .sh script didn't work (this ticket) for a mac user (it worked for
them when i told them how to use -cp instead)

b) The instructions of how to use the contents of ShefRobot.zip weren't
clear enough, people were downloading it, putting it in a directory
ShefRobot (similar to how they use sheffield package), then asking why it
can't be found.

It was explained on the documentation how to use ShefRobot.zip, just people
weren't see it because it was under instructions on how to use the sample
code. As such I'll try and make that more prominent, and duplicate it into
a ReadMe within the .zip
