### ISSUE TITLE
Open Day Program

### ISSUE THREAD

**Issue by Robadob** [ramsay-t/ShefRobot#27]
_Creating an issue because it may as-well be added as an example to the repo (similarly, if we port across the intro week robot-football task)._

I spoke with Siobhán today, and she suggested I speak with you (@ramsay-t) about what the demo task should actually be. If we can come up with something worthwhile, I can put it together over the weekend to be tested sometime next week.

Similarly if there are multiple ideas, and they're not too time consuming can just make several to see what comes out best.

**Comment by Robadob** [comment]
Someone has suggested some form of obstacle course.

Similarly Kat Roden suggested Siobháns battleships (I've no idea how battleships translates to Lego robots).

Something competitive whereby robots somehow interact would likely be ideal, however actually what and with the stuff provided in a box (that can be quickly assembled) introduces the challenge.

For a more OTT system, which would probably not link so well with the robots, could include something whereby the program they edit broadcasts messages over UDP to a server or similar, so you can display some kind of scoreboard on the projectors.

**Comment by ramsay-t** [comment]
I have too much on to sort this out today, but remind me next week (or on Saturday night when I’m sat supervising the Game Jam with nothing to do…)

**Comment by Robadob** [comment]
What time are you going to be there?

I told Frazer I might pop by for a nosey, so we could discuss it in person.

**Comment by ramsay-t** [comment]
8pm to 8am :)

**Comment by Robadob** [comment]
So you pulled the short straw then.

Don't think I'm required for anything Saturday night, so may aswell come by
after I've eaten. Presumably if your around that means I can also get
access to a Robot to test some of the feature's I didn't have a chance to
last weekend.

**Comment by Robadob** [comment]
Just noting these here so they're on the record.

Spoke with Steve Maddock during my supervision meeting.

He suggested that depending on how suitable the colour sensors were it could be possible to do something whereby they had to search for a coloured object.

More advanced would be to tie this to the real world, by doing some form of car-following/convoy. Whereby robots search till they find another robot and then they follow it hopefully via emergent behaviour.

**Comment by ramsay-t** [comment]
Have we got coloured lights? Set half to follow red and emit green at the back, the other half to follow green, and emit red. See if we can get a circle going ;)

Might work with coloured bricks…
