### ISSUE TITLE
OOP

### ISSUE THREAD

**Issue by Robadob** [ramsay-t/ShefRobot#3]
Currently looking at how [NXT/ICommand is laid out](https://staffwww.dcs.shef.ac.uk/people/G.Brown/campus_only/lego/api/index.html).

Appears they used a [`Motor` class](https://staffwww.dcs.shef.ac.uk/people/G.Brown/campus_only/lego/api/icommand/nxt/Motor.html), with 3 static members of type `Motor`, such that after connecting to the device motors were simply controlled via:

```
Motor.A.setSpeed(mySpeed);
Motor.A.forward();
```

Whereas sensors had to be instantiated, due to the different types (e.g. [push sensor offers bool](https://staffwww.dcs.shef.ac.uk/people/G.Brown/campus_only/lego/api/icommand/nxt/TouchSensor.html), whereas [ultrasound offered float](https://staffwww.dcs.shef.ac.uk/people/G.Brown/campus_only/lego/api/icommand/nxt/UltrasonicSensor.html)), so their usage was:

```
LightSensor sensorLight = new LightSensor(SensorPort.S1); 
sensorLight.activate();
int currentLight = sensorLight.getLightPercent();
sensorLight.passivate();
```

or

```
UltrasonicSensor sensorSonic = new UltrasonicSensor(SensorPort.S4);
int currentDist = sensorSonic.getDistance();
```

or

```
TouchSensor sensorTouch = new TouchSensor(SensorPort.S3); 
sensorTouch.isPressed()
```

I was inclined to create 3 sub-packages; 
- `internal` for stuff like `PortManager`
- `motor` to contain Large and Regular classes (The classes should then be referred to via `motor.Large` , rather than simply `Large`, all inheriting from an abstract motor) 
- `sensor` to contain Ultrasound, IR, Push etc (In the same style as the motor subpackage, inheriting an abstract sensor, that offers `getRawValue()`, whereas specific sensors would be able to offer `getPushed()` or similar allowing their range of values to be documented as such.)

_However it's not possible to achieve usage like `motor.Large` this way, because packages aren't as versatile as C namespaces. The solution to achieve the same usage under Java is to create `Large` and `Small` as static nested classes within the file of `Motor`, which also extend `Motor`, this however makes Motor.java potentially huge, the javadocs generate for it fine, however as it extends a class which contains itself, you have a paradox whereby `Motor.Large.Large.Large.Large` is a completely valid type._

The more sane alternative would be to end up doubley naming them via having `LargeMotor` within the `Motor` package.

Regardless, Then to get a specific motor or sensor, there are two options for accessors to be used within `Robot`. (I prefer the look of the first, but I think the second is syntactically less dubious).
- `Motor getMotor(Motor.Port, Motor.Type)` and need to cast it to their desired type of motor
- `Motor.Large getMotorLarge(Motor.Port)` this could lead to alot of methods so it's undesirable personally

Given it's quite a significant amount of shuffling (I'm happy to do it), I'll wait for your thoughts before wasting time doing something you have no interest in.

**Comment by ramsay-t** [comment]
> Currently looking at how NXT/ICommand is laid out https://staffwww.dcs.shef.ac.uk/people/G.Brown/campus_only/lego/api/index.html.

My initial reaction is “I don’t care how they did it, we will do it the way that suits us” :)

> I was inclined to create 3 sub-packages;
> 
> internal for stuff like PortManager
> motor to contain Large and Regular classes (The classes should then be referred to via motor.Large , rather than simply Large, all inheriting from an abstract motor)
> sensor to contain Ultrasound, IR, Push etc (In the same style as the motor subpackage, inheriting an abstract sensor, that offers getRawValue(), whereas specific sensors would be able to offer getPushed() or similar allowing their range of values to be documented as such.)

This makes a reasonable amount of sense, but I think Siobhan was keen on creator methods of the form Robot.getMotor();

> However it's not possible to achieve usage like motor.Large this way, because packages aren't as versatile as C namespaces. The solution to achieve the same usage under Java is to create Large and Small as static nested classes within the file of Motor, which also extend Motor, this however makes Motor.java potentially huge, the javadocs generate for it fine, however as it extends a class which contains itself, you have a paradox whereby Motor.Large.Large.Large.Large is a completely valid type.
> 
> Its late and I’ve been drinking but you can do sub folders in packages, so you can make a ShefRobot.Motor package with classes LargeMotor and SmallMotor perfectly well. They can both inherit from an abstract class either ShefRobot.Motor.Motor (i.e. the class Motor in the package ShefRobot.Motor) or just ShefRobot.Motor (the class Motor in the package ShefRobot. Not sure whether you can have the class Motor AND the package Motor at the same level.
> 
> The more sane alternative would be to end up doubley naming them via having LargeMotor within the Motor package.
> 
> This is getting less sane, I would suggest you stop and watch TV... :)
> Regardless, Then to get a specific motor or sensor, there are two options for accessors to be used within Robot. (I prefer the look of the first, but I think the second is syntactically less dubious).
> 
> Motor getMotor(Motor.Port, Motor.Type) and need to cast it to their desired type of motor
> Motor.Large getMotorLarge(Motor.Port) this could lead to alot of methods so it's undesirable personally
> The first one should be just the constructor. The second one is just madness ;) Either it gets created by a getMotor method on the Robot, or it gets constructed directly. Bear in mind how the underlying system works, though - Large motors and Regular motors are really the same class with different types -- they have identical interfaces. Is there any advantage to making separate classes? I’m not honestly sure if it even matters which type we use, we could hide even that detail if it doesn’t matter...
> 
> Given it's quite a significant amount of shuffling (I'm happy to do it), I'll wait for your thoughts before wasting time doing something you have no interest in.

Much as I am keen to hand over the work I neither want to create something that doesn’t solve Siobhan’s problem, nor be accused of preventing you completing your literature review :) Lets review this tomorrow when I can cope with thinking about it — and I’ll email Siobhan and see if she has a strong opinion either way.

Ramsay

**Comment by Robadob** [comment]
> Not sure whether you can have the class Motor AND the package Motor at the same level.

I'm pretty sure this is possible.

> Bear in mind how the underlying system works, though - Large motors and Regular motors are really the same class with different types -- they have identical interfaces.

I've been using Motor as the example, due to the apparent similarity between motors it's potentially not the best example. However the same structure should apply to sensors.

> The first one should be just the constructor. The second one is just madness ;) Either it gets created by a getMotor method on the Robot, or it gets constructed directly.

If we have multiple types of sensor (or motor) that can be returned by getSensor(), returning say an IRSensor as a generic Sensor and requiring the user to cast it just seems messy.

> Much as I am keen to hand over the work I neither want to create something that doesn’t solve Siobhan’s problem, nor be accused of preventing you completing your literature review :) Lets review this tomorrow when I can cope with thinking about it — and I’ll email Siobhan and see if she has a strong opinion either way.

Sure, tbh I'm surprised your still responding at this time of night.

**Comment by ramsay-t** [comment]
> If we have multiple types of sensor (or motor) that can be returned by getSensor(), returning say an IRSensor as a generic Sensor and requiring the user to cast it just seems messy.

Sensors make much more sense, since we can cover the insanity of the return values - touch sensor getValue should return boolean perhaps?

> Sure, tbh I'm surprised your still responding at this time of night.
> 
> Me too, my wife says I should stop replying to emails… ;)

Ramsay

**Comment by Robadob** [comment]
Re: motors difference

It appears their difference is the values that are passed to the constructor of their superclass, so whilst they can be represented by the same object, I expect their construction should be specific to the type of motor.

Diff of them available [here](http://pastebin.com/UtmHuTvw).

**Comment by Robadob** [comment]
Closing this, should be handled as a result of the motor re-factoring ticket.
