### ISSUE TITLE
TODO: Add a shutdown hook

### ISSUE THREAD

**Issue by Robadob** [ramsay-t/ShefRobot#4]
Look into handling `ctrl+c` to allow a clean shutdown via this apparent [shutdown hook](http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Runtime.html#addShutdownHook%28java.lang.Thread%29) or similar (otherwise Robots have to be restarted, which is slow).

**Comment by Robadob** [comment]
This simple class shows how to implement a shutdown hook, presumably this could easily be integrated into `Robot`, such that `run()`, calls `close()`, although it may be worth abstracting it (somehow) such that the `run()` method isn't (easily) accessible to students. As calling `myRobot.run()` and having it shutdown their robot would be a little counter intuitive.

I've tested this in cmd and it works, I've also tested it in Notepad++'s console (seeing as that's what I primarily use), and it doesn't ever trigger, so I'm guessing that whoever made the plugin decided to use a more aggressive process kill.

I'll leave this for you to decide how to include.

``` Java
public class Test extends Thread{

    public void run() 
    {
        System.out.println("Exiting!");
    }
    public Test()
    {
        Runtime.getRuntime().addShutdownHook(this);
    }
    public static void main (String[] args)
    {
        Test t = new Test();
        while(true)
        {
            try
            {
                Thread.sleep(1000);
            }
            catch(Exception e)
            {
                System.err.println("err");
            }
        }
    }
}
```

**Comment by Robadob** [comment]
Decided to make the exiting thread an inner class, this hides it from the javadocs. Will probably integrate it into Robot.java tomorrow.

Code I tested it with below;

``` java
public class Test{

    class GracefulExiter extends Thread
    {
        private Test parent;
        public GracefulExiter(Test parent)
        {
            this.parent=parent;
        }
        public void run() 
        {
            parent.close();
        }
    }
    public Test()
    {
        Runtime.getRuntime().addShutdownHook(new GracefulExiter(this));
    }
    public void close()
    {
        System.out.println("Exiting!");
    }
    public static void main (String[] args)
    {
        Test t = new Test();
        while(true)
        {
            try
            {
                Thread.sleep(1000);
            }
            catch(Exception e)
            {
                System.err.println("err");
            }
        }
    }
}
```

**Comment by ramsay-t** [comment]
Looks good. I usually hate inner classes but this is one of the few legitimate uses :)

On 28 October 2015 23:03:35 GMT+00:00, Robert Chisholm notifications@github.com wrote:

> Decided to make the exiting thread an inner class, this hides it from
> the javadocs. Will probably integrate it into Robot.java tomorrow.
> 
> Code I tested it with below;
> 
> ``` java
> public class Test{
> 
>    class GracefulExiter extends Thread
>    {
>        private Test parent;
>        public GracefulExiter(Test parent)
>        {
>            this.parent=parent;
>        }
>        public void run() 
>        {
>            parent.close();
>        }
>    }
>    public Test()
>    {
>        Runtime.getRuntime().addShutdownHook(new GracefulExiter(this));
>    }
>    public void close()
>    {
>        System.out.println("Exiting!");
>    }
>    public static void main (String[] args)
>    {
>        Test t = new Test();
>        while(true)
>        {
>            try
>            {
>                Thread.sleep(1000);
>            }
>            catch(Exception e)
>            {
>                System.err.println("err");
>            }
>        }
>    }
> }
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ramsay-t/ShefRobot/issues/4#issuecomment-152023763

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Robadob** [comment]
Will also need to wrap the addShutdownHook in a try-catch, throws errors for;
- IllegalArgumentException - If the specified hook has already been registered, or if it can be determined that the hook is already running or has already been run
- IllegalStateException - If the virtual machine is already in the process of shutting down
- SecurityException - If a security manager is present and it denies `RuntimePermission("shutdownHooks")` _Let's hope CICS haven't blocked this to_

**Comment by ramsay-t** [comment]
The second and third ones need to throw RuntimeException("Please tell Rob or Ramsay to talk to CICS");

;)

On 29 October 2015 07:16:42 GMT+00:00, Robert Chisholm notifications@github.com wrote:

> Will also need to wrap the addShutdownHook in a try-catch, throws
> errors for;
> - IllegalArgumentException - If the specified hook has already been
>   registered, or if it can be determined that the hook is already running
>   or has already been run
> - IllegalStateException - If the virtual machine is already in the
>   process of shutting down
> - SecurityException - If a security manager is present and it denies
>   `RuntimePermission("shutdownHooks")` _Let's hope CICS haven't blocked
>   this to_
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ramsay-t/ShefRobot/issues/4#issuecomment-152100421

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Robadob** [comment]
The second one is referring to if the program is already in the process of shutting down, I don't think it should be a problem. I had it thrown when I attempted to remove a shutdown hook, within my graceful exit thread.

**Comment by Robadob** [comment]
This has been confirmed to work (when killed via ctrl+c in cmd), as expected it doesn't work the same in NPPExec.
